### ISSUE TITLE
关于AdminController

### ISSUE THREAD

**Issue by Chakery** [sectong/yidongyi#1]
如果后台的功能越来越多，那么`AdminController`就会越来越臃肿，这个问题怎么解决呢？还望指教！Thx~

**Comment by jiekechoo** [comment]
这个非常容易解决，启用一个新的目录，把所有的Admin相关的Controller分解成一个个小类，丢进这个目录就搞定了。

**Comment by Chakery** [comment]
Get，感谢您的解答。
